import { object } from './builders/ObjectSchemaBuilder.js';
import { number } from './builders/NumberSchemaBuilder.js';

export {
    SchemaBuilder,
    InferType,
    MakeOptional,
    MakeRequired,
    ValidationError,
    ValidationResult
} from './builders/SchemaBuilder.js';
export { number, NumberSchemaBuilder } from './builders/NumberSchemaBuilder.js';
export { object, ObjectSchemaBuilder } from './builders/ObjectSchemaBuilder.js';

// const twenty = number().optional().equals(20);
// export const builder = object()
//     .addProp('something', number().optional())
//     .addProp('something2', number())
//     .addProp('something4', twenty)
//     .addProp('something5', twenty)
//     .addProp('something6', twenty)
//     .addProp('something7', twenty)
//     .addProp('something8', twenty)
//     .addProp('something9', twenty)
//     .addProp('something10', twenty)
//     .addProp('something11', twenty)
//     .addProp('something12', twenty)
//     .addProp('something13', twenty)
//     .addProp('something14', twenty)
//     .addProp('something15', twenty)
//     .addProp('something16', twenty)
//     .addProp('something17', twenty)
//     .addProp('something18', twenty)
//     .addProp('something19', twenty)
//     .addProp('something20', twenty)
//     .addProp('something21', twenty)
//     .addProp('something22', twenty)
//     .addProp('something23', twenty)
//     .addProp('something24', twenty)
//     .addProp('something25', twenty)
//     .addProp('something26', twenty)
//     .addProp('something27', twenty)
//     .addProp('something28', twenty)
//     .addProp('something29', twenty)
//     .addProp('something30', twenty)
//     .addProp('something31', twenty)
//     .addProp('something32', twenty)
//     .addProp('something33', twenty)
//     .addProp('something34', twenty)
//     .addProp('something35', twenty)
//     .addProp('something36', twenty)
//     .addProp('something37', twenty)
//     .addProp('something38', twenty)
//     .addProp('something39', twenty)
//     .addProp('something40', twenty)
//     .addProp('something41', twenty)
//     .addProp('something42', twenty)
//     .addProp('something43', twenty)
//     .addProp('something44', twenty)
//     .addProp('something45', twenty)
//     .addProp('something46', twenty)
//     .addProp('something47', twenty)
//     .addProp('something48', twenty)
//     .addProp('something49', twenty)
//     .addProp('something50', twenty)
//     .addProp('something51', twenty)
//     .addProp('something52', twenty)
//     .addProp('something53', twenty)
//     .addProp('something54', twenty)
//     .addProp('something55', twenty)
//     .addProp('something56', twenty)
//     .addProp('something57', twenty)
//     .addProp('something58', twenty)
//     .addProp('something59', twenty)
//     .addProp('something60', twenty)
//     .addProp('something61', twenty)
//     .addProp('something62', twenty)
//     .addProp('something63', twenty)
//     .addProp('something64', twenty)
//     .addProp('something65', twenty)
//     .addProp('something66', twenty)
//     .addProp('something67', twenty)
//     .addProp('something68', twenty)
//     .addProp('something69', twenty)
//     .addProp('something70', twenty)
//     .addProp('something71', twenty)
//     .addProp('something72', twenty)
//     .addProp('something73', twenty)
//     .addProp('something74', twenty)
//     .addProp('something75', twenty)
//     .addProp('something76', twenty)
//     .addProp('something77', twenty)
//     .addProp('something78', twenty)
//     .addProp('something79', twenty)
//     .addProp('something80', twenty)
//     .addProp('something81', twenty)
//     .addProp('something82', twenty)
//     .addProp('something83', twenty)
//     .addProp('something84', twenty)
//     .addProp('something85', twenty)
//     .addProp('something86', twenty)
//     .addProp('something87', twenty)
//     .addProp('something88', twenty)
//     .addProp('something89', twenty)
//     .addProp('something90', twenty)
//     .addProp('something91', twenty)
//     .addProp('something92', twenty)
//     .addProp('something93', twenty)
//     .addProp('something94', twenty)
//     .addProp('something95', twenty)
//     .addProp('something96', twenty)
//     .addProp('something97', twenty)
//     .addProp('something98', twenty)
//     .addProp('something99', twenty)
//     .addProp('something100', twenty)
//     .addProp('something101', twenty)
//     .addProp('something102', twenty)
//     .addProp('something103', twenty)
//     .addProp('something104', twenty)
//     .addProp('something105', twenty)
//     .addProp('something106', twenty)
//     .addProp('something107', twenty)
//     .addProp('something108', twenty)
//     .addProp('something109', twenty)
//     .addProp('something110', twenty)
//     .addProp('something111', twenty)
//     .addProp('something112', twenty)
//     .addProp('something113', twenty)
//     .addProp('something114', twenty)
//     .addProp('something115', twenty)
//     .addProp('something116', twenty)
//     .addProp('something117', twenty)
//     .addProp('something118', twenty)
//     .addProp('something119', twenty)
//     .addProp('something120', twenty)
//     .addProp('something121', twenty)
//     .addProp('something122', twenty)
//     .addProp('something123', twenty)
//     .addProp('something124', twenty)
//     .addProp('something125', twenty)
//     .addProp('something126', twenty)
//     .addProp('something127', twenty)
//     .addProp('something128', twenty)
//     .addProp('something129', twenty)
//     .addProp('something130', twenty)
//     .addProp('something131', twenty)
//     .addProp('something132', twenty)
//     .addProp('something133', twenty)
//     .addProp('something134', twenty)
//     .addProp('something135', twenty)
//     .addProp('something136', twenty)
//     .addProp('something137', twenty)
//     .addProp('something138', twenty)
//     .addProp('something139', twenty)
//     .addProp('something140', twenty)
//     .addProp('something141', twenty)
//     .addProp('something142', twenty)
//     .addProp('something143', twenty)
//     .addProp('something144', twenty)
//     .addProp('something145', twenty)
//     .addProp('something146', twenty)
//     .addProp('something147', twenty)
//     .addProp('something148', twenty)
//     .addProp('something149', twenty)
//     .addProp('something150', twenty)
//     .addProp('something151', twenty)
//     .addProp('something152', twenty)
//     .addProp('something153', twenty)
//     .addProp('something154', twenty)
//     .addProp('something155', twenty)
//     .addProp('something156', twenty)
//     .addProp('something157', twenty)
//     .addProp('something158', twenty)
//     .addProp('something159', twenty)
//     .addProp('something160', twenty)
//     .addProp('something161', twenty)
//     .addProp('something162', twenty)
//     .addProp('something163', twenty)
//     .addProp('something164', twenty)
//     .addProp('something165', twenty)
//     .addProp('something166', twenty)
//     .addProp('something167', twenty)
//     .addProp('something168', twenty)
//     .addProp('something169', twenty)
//     .addProp('something170', twenty)
//     .addProp('something171', twenty)
//     .addProp('something172', twenty)
//     .addProp('something173', twenty)
//     .addProp('something174', twenty)
//     .addProp('something175', twenty)
//     .addProp('something176', twenty)
//     .addProp('something177', twenty)
//     .addProp('something178', twenty)
//     .addProp('something179', twenty)
//     .addProp('something180', twenty)
//     .addProp('something181', twenty)
//     .addProp('something182', twenty)
//     .addProp('something183', twenty)
//     .addProp('something184', twenty)
//     .addProp('something185', twenty)
//     .addProp('something186', twenty)
//     .addProp('something187', twenty)
//     .addProp('something188', twenty)
//     .addProp('something189', twenty)
//     .addProp('something190', twenty)
//     .addProp('something191', twenty)
//     .addProp('something192', twenty)
//     .addProp('something193', twenty)
//     .addProp('something194', twenty)
//     .addProp('something195', twenty)
//     .addProp('something196', twenty)
//     .addProp('something197', twenty)
//     .addProp('something198', twenty)
//     .addProp('something199', twenty)
//     .addProp('something200', twenty)
//     .addProp('something201', twenty)
//     .addProp('something202', twenty)
//     .addProp('something203', twenty)
//     .addProp('something204', twenty)
//     .addProp('something205', twenty)
//     .addProp('something206', twenty)
//     .addProp('something207', twenty)
//     .addProp('something208', twenty)
//     .addProp('something209', twenty)
//     .addProp('something210', twenty)
//     .addProp('something211', twenty)
//     .addProp('something212', twenty)
//     .addProp('something213', twenty)
//     .addProp('something214', twenty)
//     .addProp('something215', twenty)
//     .addProp('something216', twenty)
//     .addProp('something217', twenty)
//     .addProp('something218', twenty)
//     .addProp('something219', twenty)
//     .addProp('something220', twenty)
//     .addProp('something221', twenty)
//     .addProp('something222', twenty)
//     .addProp('something223', twenty)
//     .addProp('something224', twenty)
//     .addProp('something225', twenty)
//     .addProp('something226', twenty)
//     .addProp('something227', twenty)
//     .addProp('something228', twenty)
//     .addProp('something229', twenty)
//     .addProp('something230', twenty)
//     .addProp('something231', twenty)
//     .addProp('something232', twenty)
//     .addProp('something233', twenty)
//     .addProp('something234', twenty)
//     .addProp('something235', twenty)
//     .addProp('something236', twenty)
//     .addProp('something237', twenty)
//     .addProp('something238', twenty)
//     .addProp('something239', twenty)
//     .addProp('something240', twenty)
//     .addProp('something241', twenty)
//     .addProp('something242', twenty)
//     .addProp('something243', twenty)
//     .addProp('something244', twenty)
//     .addProp('something245', twenty)
//     .addProp('something246', twenty)
//     .addProp('something247', twenty)
//     .addProp('something248', twenty)
//     .addProp('something249', twenty)
//     .addProp('something250', twenty)
//     .addProp('something251', twenty)
//     .addProp('something252', twenty)
//     .addProp('something253', twenty)
//     .addProp('something254', twenty)
//     .addProps({
//         p1: number(),
//         p2: number().optional(),
//         nested: object({
//             /**
//              * some description
//              */
//             n1: number(),
//             n2: number()
//         })
//             .optional()
//             .addProp('n3', number())
//             .addProps({
//                 n4: number(),
//                 n5: number().optional()
//             })
//     })
//     .omit('p1')
//     .optimize();

export const obj = object({
    /**
     * some comment here
     */
    first: number()
});
