/**
 * Query key utilities for `@cleverbrush/react-query`.
 *
 * Query keys follow TanStack Query's array-based convention:
 * ```
 * [PREFIX, groupName, endpointName, args?]
 * ```
 * This structure allows hierarchical invalidation — invalidate an entire
 * group with `buildGroupQueryKey(group)`, or a specific endpoint/args
 * combination with `buildQueryKey(group, endpoint, args)`.
 *
 * @module
 */

/**
 * Prefix used for all query keys generated by `@cleverbrush/react-query`.
 *
 * This ensures keys do not collide with other TanStack Query consumers
 * in the same application.
 */
export const QUERY_KEY_PREFIX = '@cleverbrush' as const;

/**
 * Builds a query key array for a specific endpoint call.
 *
 * @param group - The API group name (e.g. `'todos'`).
 * @param endpoint - The endpoint name within the group (e.g. `'list'`).
 * @param args - Optional request arguments (params, query, body, headers).
 *               Included in the key when provided so that different argument
 *               combinations produce distinct cache entries.
 * @returns A readonly query key array suitable for TanStack Query.
 *
 * @example
 * ```ts
 * buildQueryKey('todos', 'list');
 * // ['@cleverbrush', 'todos', 'list']
 *
 * buildQueryKey('todos', 'list', { query: { page: 2 } });
 * // ['@cleverbrush', 'todos', 'list', { query: { page: 2 } }]
 *
 * buildQueryKey('todos', 'get', { params: { id: 42 } });
 * // ['@cleverbrush', 'todos', 'get', { params: { id: 42 } }]
 * ```
 */
export function buildQueryKey(
    group: string,
    endpoint: string,
    args?: unknown
): readonly unknown[] {
    if (args !== undefined) {
        return [QUERY_KEY_PREFIX, group, endpoint, args] as const;
    }
    return [QUERY_KEY_PREFIX, group, endpoint] as const;
}

/**
 * Builds a query key array for an entire API group.
 *
 * Use this with `queryClient.invalidateQueries()` to invalidate
 * all cached queries belonging to a group at once.
 *
 * @param group - The API group name (e.g. `'todos'`).
 * @returns A readonly query key array that is a prefix of all endpoint
 *          keys within the group.
 *
 * @example
 * ```ts
 * buildGroupQueryKey('todos');
 * // ['@cleverbrush', 'todos']
 *
 * // Invalidate all todo-related queries:
 * queryClient.invalidateQueries({ queryKey: buildGroupQueryKey('todos') });
 * ```
 */
export function buildGroupQueryKey(group: string): readonly unknown[] {
    return [QUERY_KEY_PREFIX, group] as const;
}
